<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>vmixer</AssemblyName>
    <RootNamespace>VirtualMixer</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <!-- NAudio meta-package bundles NAudio.Core / .Wasapi / .MediaFoundation, etc. -->
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>
